services:
  app:
    build:
      context: .

    container_name: "online_App"
    ports:
      - "5173:5173"
    
    restart: always

    healthcheck:
      test: [ "CMD", "curl", "-f","http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

    volumes:
      - "online_shop:/app/volume/"
      

volumes:
  online_shop:


